### PR TITLE
fix(java): fix big integer serialization

### LINKED ISSUE #1478: Failed to serialize BigInteger
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

0.5.0-SNAPSHOT

### Component(s)

Java

### Minimal reproduce step

        BigInteger bigInteger = new BigInteger("11111111110101010000283895380202208220050200000000111111111");
        Fury fury = Fury.builder()
                .withLanguage(Language.JAVA)
                .requireClassRegistration(false)
                .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
                .withAsyncCompilation(true)
                .build();
        fury.serialize(bigInteger);

### What did you expect to see?

Be serialized to a byte[]

### What did you see instead?

java.lang.IllegalArgumentException
	at org.apache.fury.util.Preconditions.checkArgument(Preconditions.java:46)
	at org.apache.fury.serializer.Serializers$BigIntegerSerializer.write(Serializers.java:365)
	at org.apache.fury.serializer.Serializers$BigIntegerSerializer.write(Serializers.java:357)
	at org.apache.fury.Fury.writeData(Fury.java:555)
	at org.apache.fury.Fury.writeRef(Fury.java:348)
	at org.apache.fury.Fury.write(Fury.java:323)
	at org.apache.fury.Fury.serialize(Fury.java:251)
	at org.apache.fury.Fury.serialize(Fury.java:199)

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by chaokunyang**
Closes #1478

### CODE REVIEW

File: java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java [hunk 1]
```diff
@@ -364,14 +364,13 @@ public BigIntegerSerializer(Fury fury) {
     @Override
     public void write(MemoryBuffer buffer, BigInteger value) {
       final byte[] bytes = value.toByteArray();
-      Preconditions.checkArgument(bytes.length <= 16);
-      buffer.writeByte((byte) bytes.length);
+      buffer.writePositiveVarInt((byte) bytes.length);
```
Comment (LiangliangSui) [inline java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java:367]: Directly pass in `bytes.length` to `writePositiveVarInt`. Why do you need to convert it to byte? This will cause truncation.

**Review by LiangliangSui — CHANGES_REQUESTED** [review]

File: java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java (hunk 1 above)
Comment (chaokunyang) [reply java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java]: Nice catch, fixed

**Review by LiangliangSui — APPROVED** [review]
LGTM, thanks for fixing this issue.
